cohorts:
- name: test
  features_config: default
  fields: []
  weight: 1.0
  model:
    name: NoOp
database:
  type: memory
features:
  default:
    raw: json_expand
    raw.score: numeric
    raw.meta: json_expand
    raw.meta.version: semver
