cohorts:
- name: test
  features_config: default
  fields: []
  weight: 1.0
  warmup_count: 16
  model:
    name: Autoencoder
    params:
      buffer_size: 200
      retrain_every: 50
      epochs_per_retrain: 10
      seed: 42
database:
  type: memory
features:
  default:
    browser: str_categorical
