cohorts:
- name: test
  features_config: default
  fields: []
  weight: 1.0
  model:
    name: Autoencoder
    params:
      buffer_size: 200
      min_buffer_size: 20
      retrain_every: 20
      epochs_per_retrain: 2
      embed_dim: 32
      seed: 42

database:
  type: memory

identifiers:
  - description

features:
  default:
    message:
      type: str_text
      preprocessor:
        name: SentenceTransformerEncoder
        params:
          embed_dim: 32

results:
  f1: 0.0
  recall: 0.0
  precision: 0.0
  tp: 0
  fp: 0
  tn: 4
  fn: 1
