cohorts:
- name: test
  features_config: default
  fields: []
  weight: 1.0
  model:
    name: NoOp
database:
  type: memory
features:
  default:
    country:
      type: str_categorical
      preprocessor:
        name: OneHotEncoder
        params:
          n_categories: 5
