cohorts:
  - name: "global"
    features_config: "default"
    fields: []
    weight: 1
    model:
      name: Autoencoder
      params:
        buffer_size: 2500
        min_buffer_size: 100
        retrain_every: 25
        epochs_per_retrain: 2
        seed: 42

database:
  type: memory

identifiers:
  - description

features:
  default:
    timestamp: timestamp
    user.id: str_categorical
    user.department: str_categorical
    ip.country_iso: str_categorical
    client.os: str_categorical
    client.browser: str_categorical
    latency: numeric

results:
  f1: 0.8
  recall: 0.8
  precision: 0.8
  tp: 16
  fp: 4
  tn: 16
  fn: 4
