cohorts:
  - name: "global"
    features_config: "default"
    fields: []
    weight: 1
    warmup_count: 100
    model:
      name: Autoencoder
      params:
        buffer_size: 2500
        retrain_every: 25
        epochs_per_retrain: 2
        seed: 42

database:
  type: memory

identifiers:
  - description

features:
  default:
    timestamp: timestamp
    user.id: str_categorical
    user.department: str_categorical
    ip.country_iso: str_categorical
    client.os: str_categorical
    client.browser: str_categorical
    latency: numeric

results:
  f1: 0.926829
  recall: 0.95
  precision: 0.904762
  tp: 19
  fp: 2
  tn: 18
  fn: 1
  fp_scores: [81.25, 95.8]
  fn_scores: [30.08]
