cohorts:
  - name: "global"
    features_config: "default"
    fields: []
    weight: 1
    warmup_count: 100
    model:
      name: Autoencoder
      params:
        buffer_size: 2500
        retrain_every: 25
        epochs_per_retrain: 2
        seed: 42

database:
  type: memory

identifiers:
  - description

features:
  default:
    timestamp: timestamp
    user.id: str_categorical
    user.department: str_categorical
    ip.country_iso: str_categorical
    client.os: str_categorical
    client.browser: str_categorical
    latency: numeric

results:
  train_count: 3996
  score_count: 48
  accepted_count: 4044
  unaccepted_count: 0
  normal_count: 25
  anomaly_count: 23
  f1: 0.930233
  recall: 0.869565
  precision: 1.0
  tp: 20
  fp: 0
  tn: 25
  fn: 3
  fp_scores: []
  fn_scores: [20.04, 15.55, 28.3]
