cohorts:
- name: user
  features_config: default
  fields:
  - user
  weight: 1.0
  lru_size: 0
  model:
    name: HalfSpaceTrees
    params:
      window_size: 10
      n_trees: 5
      height: 1
      sliding_steps: 1
database:
  type: memory
features:
  default:
    value: numeric
